const mongoose = require("mongoose");

const EventLogSchema = new mongoose.Schema(
  {
    // Unique ID generated by agent
    eventId: {
      type: String,
      required: true,
      index: true,
      unique: true
    },

    // When event happened on agent
    timestamp: {
      type: Date,
      required: true,
      index: true
    },

    // Company name from Tally
    company: {
      type: String,
      required: true,
      index: true
    },

    // Always "cron" for now (future-proof)
    source: {
      type: String,
      enum: ["cron"],
      required: true
    },

    // What data this refers to
    module: {
      type: String,
      enum: ["customers", "inventory"],
      required: true,
      index: true
    },

    // What operation was happening
    action: {
      type: String,
      enum: ["fetch", "sync"],
      required: true
    },

    // Result of the operation
    status: {
      type: String,
      enum: ["success", "error"],
      required: true,
      index: true
    },

    // Pipeline stage
    stage: {
      type: String,
      enum: ["request", "response", "hash", "sync", "error"],
      required: true
    },

    // Human readable message
    message: {
      type: String,
      required: true
    },

    // Flexible extra information
    details: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
    }
  },
  {
    collection: "event_logs",
timestamp: {
  type: Date,
  index: { expires: "90d" }
}  }
);

module.exports = mongoose.model("EventLog", EventLogSchema);
